# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

equal <- function(x) {
    .Call('_FuseSOM_equal', PACKAGE = 'FuseSOM', x)
}

rootChoose <- function(n, k, root) {
    .Call('_FuseSOM_rootChoose', PACKAGE = 'FuseSOM', n, k, root)
}

rootChooseLookup <- function(n, k, lookup) {
    .Call('_FuseSOM_rootChooseLookup', PACKAGE = 'FuseSOM', n, k, lookup)
}

rootCombLookup <- function(ns, lookup) {
    .Call('_FuseSOM_rootCombLookup', PACKAGE = 'FuseSOM', ns, lookup)
}

stabExp <- function(ns, lookup) {
    .Call('_FuseSOM_stabExp', PACKAGE = 'FuseSOM', ns, lookup)
}

lookup <- function(n = 10000L, root = 200) {
    .Call('_FuseSOM_lookup', PACKAGE = 'FuseSOM', n, root)
}

